spring.application.name=curso-spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5432/db_springboot
spring.datasource.username=postgres
spring.datasource.password=was
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


server.servlet.context-parameters.jakarta.servlet.jsp.jstl.fmt.locale=pt_BR
spring.web.locale=pt_BR
spring.web.locale-resolver=fixed
